<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.43.0 (0)
 -->
<!-- Title: %3 Pages: 1 -->
<svg width="6156pt" height="620pt"
 viewBox="0.00 0.00 6156.13 620.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 616)">
<title>%3</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-616 6152.13,-616 6152.13,4 -4,4"/>
<!-- [root] data.openstack_networking_network_v2.bastion_net (expand) -->
<g id="node1" class="node">
<title>[root] data.openstack_networking_network_v2.bastion_net (expand)</title>
<polygon fill="none" stroke="black" points="4002.62,-180 3613.62,-180 3613.62,-144 4002.62,-144 4002.62,-180"/>
<text text-anchor="middle" x="3808.12" y="-158.3" font-family="Times,serif" font-size="14.00">data.openstack_networking_network_v2.bastion_net</text>
</g>
<!-- [root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] -->
<g id="node13" class="node">
<title>[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;]</title>
<polygon fill="none" stroke="black" points="4339.12,-108 3838.24,-90 4339.12,-72 4840.01,-90 4339.12,-108"/>
<text text-anchor="middle" x="4339.12" y="-86.3" font-family="Times,serif" font-size="14.00">provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;]</text>
</g>
<!-- [root] data.openstack_networking_network_v2.bastion_net (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] -->
<g id="edge1" class="edge">
<title>[root] data.openstack_networking_network_v2.bastion_net (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;]</title>
<path fill="none" stroke="black" d="M3937.34,-143.97C4026.14,-132.26 4142.83,-116.88 4227.57,-105.71"/>
<polygon fill="black" stroke="black" points="4228.28,-109.14 4237.74,-104.37 4227.36,-102.2 4228.28,-109.14"/>
</g>
<!-- [root] var.bastion_network_name (expand, reference) -->
<g id="node20" class="node">
<title>[root] var.bastion_network_name (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="3563.12" cy="-90" rx="256.95" ry="18"/>
<text text-anchor="middle" x="3563.12" y="-86.3" font-family="Times,serif" font-size="14.00">[root] var.bastion_network_name (expand, reference)</text>
</g>
<!-- [root] data.openstack_networking_network_v2.bastion_net (expand)&#45;&gt;[root] var.bastion_network_name (expand, reference) -->
<g id="edge2" class="edge">
<title>[root] data.openstack_networking_network_v2.bastion_net (expand)&#45;&gt;[root] var.bastion_network_name (expand, reference)</title>
<path fill="none" stroke="black" d="M3748.5,-143.97C3713.01,-133.82 3667.85,-120.92 3630.99,-110.39"/>
<polygon fill="black" stroke="black" points="3631.89,-107.01 3621.32,-107.63 3629.97,-113.74 3631.89,-107.01"/>
</g>
<!-- [root] data.openstack_networking_network_v2.external (expand) -->
<g id="node2" class="node">
<title>[root] data.openstack_networking_network_v2.external (expand)</title>
<polygon fill="none" stroke="black" points="6118.62,-252 5753.62,-252 5753.62,-216 6118.62,-216 6118.62,-252"/>
<text text-anchor="middle" x="5936.12" y="-230.3" font-family="Times,serif" font-size="14.00">data.openstack_networking_network_v2.external</text>
</g>
<!-- [root] data.openstack_networking_network_v2.external (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] -->
<g id="edge3" class="edge">
<title>[root] data.openstack_networking_network_v2.external (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;]</title>
<path fill="none" stroke="black" d="M5908.94,-215.87C5873.34,-194.48 5808.26,-158.89 5747.12,-144 5645.97,-119.37 5056.7,-104.06 4673.23,-96.57"/>
<polygon fill="black" stroke="black" points="4673.15,-93.06 4663.08,-96.37 4673.01,-100.06 4673.15,-93.06"/>
</g>
<!-- [root] var.external_network_name (expand, reference) -->
<g id="node21" class="node">
<title>[root] var.external_network_name (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="5477.12" cy="-162" rx="260.75" ry="18"/>
<text text-anchor="middle" x="5477.12" y="-158.3" font-family="Times,serif" font-size="14.00">[root] var.external_network_name (expand, reference)</text>
</g>
<!-- [root] data.openstack_networking_network_v2.external (expand)&#45;&gt;[root] var.external_network_name (expand, reference) -->
<g id="edge4" class="edge">
<title>[root] data.openstack_networking_network_v2.external (expand)&#45;&gt;[root] var.external_network_name (expand, reference)</title>
<path fill="none" stroke="black" d="M5824.43,-215.97C5753.08,-205.09 5660.9,-191.03 5589.44,-180.13"/>
<polygon fill="black" stroke="black" points="5589.91,-176.66 5579.5,-178.61 5588.85,-183.58 5589.91,-176.66"/>
</g>
<!-- [root] data.openstack_networking_router_v2.bastion_router (expand) -->
<g id="node3" class="node">
<title>[root] data.openstack_networking_router_v2.bastion_router (expand)</title>
<polygon fill="none" stroke="black" points="5347.62,-396 4950.62,-396 4950.62,-360 5347.62,-360 5347.62,-396"/>
<text text-anchor="middle" x="5149.12" y="-374.3" font-family="Times,serif" font-size="14.00">data.openstack_networking_router_v2.bastion_router</text>
</g>
<!-- [root] data.openstack_networking_router_v2.bastion_router (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] -->
<g id="edge5" class="edge">
<title>[root] data.openstack_networking_router_v2.bastion_router (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;]</title>
<path fill="none" stroke="black" d="M5209.69,-359.96C5227.06,-351.96 5244.01,-340.43 5254.12,-324 5262.51,-310.37 5264.1,-300.51 5254.12,-288 5209.21,-231.7 5159.63,-285.97 5096.12,-252 5075.61,-241.03 5078.92,-226.44 5058.12,-216 4916.86,-145.08 4742.53,-113.6 4600.9,-99.96"/>
<polygon fill="black" stroke="black" points="4601.05,-96.46 4590.76,-99.01 4600.39,-103.43 4601.05,-96.46"/>
</g>
<!-- [root] var.bastion_router_name (expand, reference) -->
<g id="node22" class="node">
<title>[root] var.bastion_router_name (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="4997.12" cy="-306" rx="247.76" ry="18"/>
<text text-anchor="middle" x="4997.12" y="-302.3" font-family="Times,serif" font-size="14.00">[root] var.bastion_router_name (expand, reference)</text>
</g>
<!-- [root] data.openstack_networking_router_v2.bastion_router (expand)&#45;&gt;[root] var.bastion_router_name (expand, reference) -->
<g id="edge6" class="edge">
<title>[root] data.openstack_networking_router_v2.bastion_router (expand)&#45;&gt;[root] var.bastion_router_name (expand, reference)</title>
<path fill="none" stroke="black" d="M5111.94,-359.88C5091.1,-350.28 5064.94,-338.23 5042.85,-328.06"/>
<polygon fill="black" stroke="black" points="5044.21,-324.83 5033.66,-323.83 5041.28,-331.19 5044.21,-324.83"/>
</g>
<!-- [root] data.openstack_networking_subnet_v2.bastion_net (expand) -->
<g id="node4" class="node">
<title>[root] data.openstack_networking_subnet_v2.bastion_net (expand)</title>
<polygon fill="none" stroke="black" points="4090.62,-396 3711.62,-396 3711.62,-360 4090.62,-360 4090.62,-396"/>
<text text-anchor="middle" x="3901.12" y="-374.3" font-family="Times,serif" font-size="14.00">data.openstack_networking_subnet_v2.bastion_net</text>
</g>
<!-- [root] data.openstack_networking_subnet_v2.bastion_net (expand)&#45;&gt;[root] data.openstack_networking_network_v2.bastion_net (expand) -->
<g id="edge7" class="edge">
<title>[root] data.openstack_networking_subnet_v2.bastion_net (expand)&#45;&gt;[root] data.openstack_networking_network_v2.bastion_net (expand)</title>
<path fill="none" stroke="black" d="M3998.4,-359.97C4036.49,-351.15 4073.8,-339.04 4085.12,-324 4113.99,-285.65 4115.71,-252.99 4085.12,-216 4072.47,-200.69 4040.02,-189.77 4001.59,-181.98"/>
<polygon fill="black" stroke="black" points="4002.18,-178.53 3991.7,-180.07 4000.85,-185.4 4002.18,-178.53"/>
</g>
<!-- [root] module.bastion.data.openstack_images_image_v2.this (expand) -->
<g id="node5" class="node">
<title>[root] module.bastion.data.openstack_images_image_v2.this (expand)</title>
<polygon fill="none" stroke="black" points="3369.12,-324 2967.12,-324 2967.12,-288 3369.12,-288 3369.12,-324"/>
<text text-anchor="middle" x="3168.12" y="-302.3" font-family="Times,serif" font-size="14.00">module.bastion.data.openstack_images_image_v2.this</text>
</g>
<!-- [root] module.bastion.data.openstack_images_image_v2.this (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] -->
<g id="edge12" class="edge">
<title>[root] module.bastion.data.openstack_images_image_v2.this (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;]</title>
<path fill="none" stroke="black" d="M3281.35,-287.96C3314.51,-280.04 3349.94,-268.56 3380.12,-252 3400.52,-240.81 3396.78,-225.26 3418.12,-216 3539.43,-163.35 3881.9,-203.01 4012.12,-180 4067.38,-170.24 4079.06,-158.99 4133.12,-144 4178.07,-131.54 4228.8,-118.47 4268.68,-108.43"/>
<polygon fill="black" stroke="black" points="4269.73,-111.78 4278.57,-105.95 4268.02,-104.99 4269.73,-111.78"/>
</g>
<!-- [root] module.bastion.var.image_name (expand, reference) -->
<g id="node26" class="node">
<title>[root] module.bastion.var.image_name (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="3089.12" cy="-234" rx="282.15" ry="18"/>
<text text-anchor="middle" x="3089.12" y="-230.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.image_name (expand, reference)</text>
</g>
<!-- [root] module.bastion.data.openstack_images_image_v2.this (expand)&#45;&gt;[root] module.bastion.var.image_name (expand, reference) -->
<g id="edge11" class="edge">
<title>[root] module.bastion.data.openstack_images_image_v2.this (expand)&#45;&gt;[root] module.bastion.var.image_name (expand, reference)</title>
<path fill="none" stroke="black" d="M3148.6,-287.7C3138.74,-278.97 3126.64,-268.24 3115.93,-258.75"/>
<polygon fill="black" stroke="black" points="3118.23,-256.12 3108.43,-252.1 3113.59,-261.36 3118.23,-256.12"/>
</g>
<!-- [root] module.bastion.openstack_compute_floatingip_associate_v2.this (expand) -->
<g id="node6" class="node">
<title>[root] module.bastion.openstack_compute_floatingip_associate_v2.this (expand)</title>
<polygon fill="none" stroke="black" points="3693.62,-396 3220.62,-396 3220.62,-360 3693.62,-360 3693.62,-396"/>
<text text-anchor="middle" x="3457.12" y="-374.3" font-family="Times,serif" font-size="14.00">module.bastion.openstack_compute_floatingip_associate_v2.this</text>
</g>
<!-- [root] module.bastion.openstack_compute_floatingip_associate_v2.this (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] -->
<g id="edge14" class="edge">
<title>[root] module.bastion.openstack_compute_floatingip_associate_v2.this (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;]</title>
<path fill="none" stroke="black" d="M3685.92,-359.99C3858.78,-346.73 4067.8,-329.65 4076.12,-324 4150.13,-273.77 4097.84,-201.77 4166.12,-144 4186.22,-127 4211.69,-115.45 4236.87,-107.6"/>
<polygon fill="black" stroke="black" points="4237.89,-110.95 4246.5,-104.77 4235.92,-104.24 4237.89,-110.95"/>
</g>
<!-- [root] module.bastion (expand) -->
<g id="node27" class="node">
<title>[root] module.bastion (expand)</title>
<ellipse fill="none" stroke="black" cx="2598.12" cy="-90" rx="154.07" ry="18"/>
<text text-anchor="middle" x="2598.12" y="-86.3" font-family="Times,serif" font-size="14.00">[root] module.bastion (expand)</text>
</g>
<!-- [root] module.bastion.openstack_compute_floatingip_associate_v2.this (expand)&#45;&gt;[root] module.bastion (expand) -->
<g id="edge13" class="edge">
<title>[root] module.bastion.openstack_compute_floatingip_associate_v2.this (expand)&#45;&gt;[root] module.bastion (expand)</title>
<path fill="none" stroke="black" d="M3687.9,-359.99C3852.45,-347.29 4045.73,-330.99 4052.12,-324 4084.52,-288.59 4084.67,-251.28 4052.12,-216 4018.33,-179.38 3654.64,-185.54 3605.12,-180 3493.13,-167.47 3466.19,-155.95 3354.12,-144 3144.22,-121.62 2900.48,-106.47 2747.76,-98.29"/>
<polygon fill="black" stroke="black" points="2747.55,-94.77 2737.38,-97.73 2747.18,-101.76 2747.55,-94.77"/>
</g>
<!-- [root] module.bastion.openstack_compute_instance_v2.this (expand) -->
<g id="node7" class="node">
<title>[root] module.bastion.openstack_compute_instance_v2.this (expand)</title>
<polygon fill="none" stroke="black" points="2869.62,-396 2476.62,-396 2476.62,-360 2869.62,-360 2869.62,-396"/>
<text text-anchor="middle" x="2673.12" y="-374.3" font-family="Times,serif" font-size="14.00">module.bastion.openstack_compute_instance_v2.this</text>
</g>
<!-- [root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.data.openstack_images_image_v2.this (expand) -->
<g id="edge15" class="edge">
<title>[root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.data.openstack_images_image_v2.this (expand)</title>
<path fill="none" stroke="black" d="M2793.58,-359.97C2867.39,-349.53 2961.88,-336.17 3037.49,-325.47"/>
<polygon fill="black" stroke="black" points="3038.14,-328.92 3047.56,-324.05 3037.16,-321.98 3038.14,-328.92"/>
</g>
<!-- [root] module.bastion.var.instance_name (expand, reference) -->
<g id="node28" class="node">
<title>[root] module.bastion.var.instance_name (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="1491.12" cy="-306" rx="293.25" ry="18"/>
<text text-anchor="middle" x="1491.12" y="-302.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.instance_name (expand, reference)</text>
</g>
<!-- [root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.instance_name (expand, reference) -->
<g id="edge16" class="edge">
<title>[root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.instance_name (expand, reference)</title>
<path fill="none" stroke="black" d="M2476.61,-365.36C2263.26,-352.73 1923.68,-332.62 1704.09,-319.61"/>
<polygon fill="black" stroke="black" points="1704.24,-316.11 1694.05,-319.02 1703.82,-323.1 1704.24,-316.11"/>
</g>
<!-- [root] module.bastion.var.instance_type (expand, reference) -->
<g id="node29" class="node">
<title>[root] module.bastion.var.instance_type (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="892.12" cy="-306" rx="287.85" ry="18"/>
<text text-anchor="middle" x="892.12" y="-302.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.instance_type (expand, reference)</text>
</g>
<!-- [root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.instance_type (expand, reference) -->
<g id="edge17" class="edge">
<title>[root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.instance_type (expand, reference)</title>
<path fill="none" stroke="black" d="M2476.53,-371.32C2192.34,-362.81 1650.26,-345.43 1189.12,-324 1160.86,-322.69 1131.09,-321.16 1101.75,-319.56"/>
<polygon fill="black" stroke="black" points="1101.57,-316.05 1091.39,-319 1101.19,-323.04 1101.57,-316.05"/>
</g>
<!-- [root] module.bastion.var.keypair_name (expand, reference) -->
<g id="node30" class="node">
<title>[root] module.bastion.var.keypair_name (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="2091.12" cy="-306" rx="288.65" ry="18"/>
<text text-anchor="middle" x="2091.12" y="-302.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.keypair_name (expand, reference)</text>
</g>
<!-- [root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.keypair_name (expand, reference) -->
<g id="edge18" class="edge">
<title>[root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.keypair_name (expand, reference)</title>
<path fill="none" stroke="black" d="M2531.49,-359.97C2439.07,-348.85 2319.05,-334.41 2227.66,-323.42"/>
<polygon fill="black" stroke="black" points="2227.85,-319.92 2217.51,-322.2 2227.02,-326.87 2227.85,-319.92"/>
</g>
<!-- [root] module.bastion.var.network_id (expand, reference) -->
<g id="node31" class="node">
<title>[root] module.bastion.var.network_id (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="2673.12" cy="-306" rx="275.65" ry="18"/>
<text text-anchor="middle" x="2673.12" y="-302.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.network_id (expand, reference)</text>
</g>
<!-- [root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.network_id (expand, reference) -->
<g id="edge19" class="edge">
<title>[root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.network_id (expand, reference)</title>
<path fill="none" stroke="black" d="M2673.12,-359.7C2673.12,-351.98 2673.12,-342.71 2673.12,-334.11"/>
<polygon fill="black" stroke="black" points="2676.62,-334.1 2673.12,-324.1 2669.62,-334.1 2676.62,-334.1"/>
</g>
<!-- [root] module.bastion.var.security_group_names (expand, reference) -->
<g id="node32" class="node">
<title>[root] module.bastion.var.security_group_names (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="3715.12" cy="-306" rx="328.44" ry="18"/>
<text text-anchor="middle" x="3715.12" y="-302.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.security_group_names (expand, reference)</text>
</g>
<!-- [root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.security_group_names (expand, reference) -->
<g id="edge20" class="edge">
<title>[root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.security_group_names (expand, reference)</title>
<path fill="none" stroke="black" d="M2869.73,-363.79C3051.43,-351.59 3320.55,-333.51 3506.11,-321.04"/>
<polygon fill="black" stroke="black" points="3506.52,-324.52 3516.26,-320.36 3506.05,-317.54 3506.52,-324.52"/>
</g>
<!-- [root] module.bastion.var.ssh_public_key (expand, reference) -->
<g id="node33" class="node">
<title>[root] module.bastion.var.ssh_public_key (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="293.12" cy="-306" rx="293.25" ry="18"/>
<text text-anchor="middle" x="293.12" y="-302.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.ssh_public_key (expand, reference)</text>
</g>
<!-- [root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.ssh_public_key (expand, reference) -->
<g id="edge21" class="edge">
<title>[root] module.bastion.openstack_compute_instance_v2.this (expand)&#45;&gt;[root] module.bastion.var.ssh_public_key (expand, reference)</title>
<path fill="none" stroke="black" d="M2476.44,-374C2107.48,-367.92 1286.31,-352.26 595.12,-324 565.66,-322.8 534.59,-321.3 504.04,-319.7"/>
<polygon fill="black" stroke="black" points="503.88,-316.19 493.7,-319.16 503.51,-323.18 503.88,-316.19"/>
</g>
<!-- [root] module.bastion.openstack_networking_floatingip_v2.this (expand) -->
<g id="node8" class="node">
<title>[root] module.bastion.openstack_networking_floatingip_v2.this (expand)</title>
<polygon fill="none" stroke="black" points="5885.12,-396 5465.12,-396 5465.12,-360 5885.12,-360 5885.12,-396"/>
<text text-anchor="middle" x="5675.12" y="-374.3" font-family="Times,serif" font-size="14.00">module.bastion.openstack_networking_floatingip_v2.this</text>
</g>
<!-- [root] module.bastion.openstack_networking_floatingip_v2.this (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] -->
<g id="edge23" class="edge">
<title>[root] module.bastion.openstack_networking_floatingip_v2.this (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;]</title>
<path fill="none" stroke="black" d="M5885.22,-367.19C6038.26,-352 6206.2,-313.47 6128.12,-216 6036.44,-101.55 5951.57,-162.73 5806.12,-144 5597.57,-117.15 5048.33,-102.89 4684.28,-96.15"/>
<polygon fill="black" stroke="black" points="4684.16,-92.65 4674.1,-95.96 4684.03,-99.65 4684.16,-92.65"/>
</g>
<!-- [root] module.bastion.var.external_network_name (expand, reference) -->
<g id="node34" class="node">
<title>[root] module.bastion.var.external_network_name (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="5738.12" cy="-306" rx="334.94" ry="18"/>
<text text-anchor="middle" x="5738.12" y="-302.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.external_network_name (expand, reference)</text>
</g>
<!-- [root] module.bastion.openstack_networking_floatingip_v2.this (expand)&#45;&gt;[root] module.bastion.var.external_network_name (expand, reference) -->
<g id="edge22" class="edge">
<title>[root] module.bastion.openstack_networking_floatingip_v2.this (expand)&#45;&gt;[root] module.bastion.var.external_network_name (expand, reference)</title>
<path fill="none" stroke="black" d="M5690.7,-359.7C5698.33,-351.22 5707.65,-340.86 5716,-331.58"/>
<polygon fill="black" stroke="black" points="5718.64,-333.88 5722.73,-324.1 5713.44,-329.2 5718.64,-333.88"/>
</g>
<!-- [root] openstack_compute_keypair_v2.operator (expand) -->
<g id="node9" class="node">
<title>[root] openstack_compute_keypair_v2.operator (expand)</title>
<polygon fill="none" stroke="black" points="2532.62,-180 2225.62,-180 2225.62,-144 2532.62,-144 2532.62,-180"/>
<text text-anchor="middle" x="2379.12" y="-158.3" font-family="Times,serif" font-size="14.00">openstack_compute_keypair_v2.operator</text>
</g>
<!-- [root] openstack_compute_keypair_v2.operator (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] -->
<g id="edge48" class="edge">
<title>[root] openstack_compute_keypair_v2.operator (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;]</title>
<path fill="none" stroke="black" d="M2532.68,-151.71C2581.12,-148.98 2634.85,-146.15 2684.12,-144 3192.78,-121.83 3320.25,-124.48 3829.12,-108 3912.23,-105.31 4002.96,-102.31 4084.54,-99.58"/>
<polygon fill="black" stroke="black" points="4085.08,-103.06 4094.96,-99.23 4084.84,-96.07 4085.08,-103.06"/>
</g>
<!-- [root] var.operator_ssh_public_key_path (expand, reference) -->
<g id="node44" class="node">
<title>[root] var.operator_ssh_public_key_path (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="1735.12" cy="-90" rx="288.65" ry="18"/>
<text text-anchor="middle" x="1735.12" y="-86.3" font-family="Times,serif" font-size="14.00">[root] var.operator_ssh_public_key_path (expand, reference)</text>
</g>
<!-- [root] openstack_compute_keypair_v2.operator (expand)&#45;&gt;[root] var.operator_ssh_public_key_path (expand, reference) -->
<g id="edge49" class="edge">
<title>[root] openstack_compute_keypair_v2.operator (expand)&#45;&gt;[root] var.operator_ssh_public_key_path (expand, reference)</title>
<path fill="none" stroke="black" d="M2225.28,-144.28C2121.21,-132.97 1984.58,-118.11 1882.01,-106.97"/>
<polygon fill="black" stroke="black" points="1882.2,-103.47 1871.88,-105.86 1881.44,-110.43 1882.2,-103.47"/>
</g>
<!-- [root] openstack_networking_secgroup_rule_v2.egress_all (expand) -->
<g id="node10" class="node">
<title>[root] openstack_networking_secgroup_rule_v2.egress_all (expand)</title>
<polygon fill="none" stroke="black" points="4491.62,-396 4108.62,-396 4108.62,-360 4491.62,-360 4491.62,-396"/>
<text text-anchor="middle" x="4300.12" y="-374.3" font-family="Times,serif" font-size="14.00">openstack_networking_secgroup_rule_v2.egress_all</text>
</g>
<!-- [root] openstack_networking_secgroup_v2.bastion (expand) -->
<g id="node12" class="node">
<title>[root] openstack_networking_secgroup_v2.bastion (expand)</title>
<polygon fill="none" stroke="black" points="4503.62,-180 4174.62,-180 4174.62,-144 4503.62,-144 4503.62,-180"/>
<text text-anchor="middle" x="4339.12" y="-158.3" font-family="Times,serif" font-size="14.00">openstack_networking_secgroup_v2.bastion</text>
</g>
<!-- [root] openstack_networking_secgroup_rule_v2.egress_all (expand)&#45;&gt;[root] openstack_networking_secgroup_v2.bastion (expand) -->
<g id="edge50" class="edge">
<title>[root] openstack_networking_secgroup_rule_v2.egress_all (expand)&#45;&gt;[root] openstack_networking_secgroup_v2.bastion (expand)</title>
<path fill="none" stroke="black" d="M4246.9,-359.96C4230.23,-351.84 4213.7,-340.23 4204.12,-324 4195.99,-310.22 4197.72,-302.66 4204.12,-288 4223.73,-243.13 4268.26,-207.17 4300.84,-185.55"/>
<polygon fill="black" stroke="black" points="4302.77,-188.47 4309.26,-180.1 4298.97,-182.59 4302.77,-188.47"/>
</g>
<!-- [root] openstack_networking_secgroup_rule_v2.ssh_from_home (expand) -->
<g id="node11" class="node">
<title>[root] openstack_networking_secgroup_rule_v2.ssh_from_home (expand)</title>
<polygon fill="none" stroke="black" points="4932.12,-396 4510.12,-396 4510.12,-360 4932.12,-360 4932.12,-396"/>
<text text-anchor="middle" x="4721.12" y="-374.3" font-family="Times,serif" font-size="14.00">openstack_networking_secgroup_rule_v2.ssh_from_home</text>
</g>
<!-- [root] openstack_networking_secgroup_rule_v2.ssh_from_home (expand)&#45;&gt;[root] openstack_networking_secgroup_v2.bastion (expand) -->
<g id="edge51" class="edge">
<title>[root] openstack_networking_secgroup_rule_v2.ssh_from_home (expand)&#45;&gt;[root] openstack_networking_secgroup_v2.bastion (expand)</title>
<path fill="none" stroke="black" d="M4721.74,-359.73C4721.54,-340.31 4718.42,-308.75 4702.12,-288 4656.63,-230.04 4582.73,-198.83 4513.45,-182.07"/>
<polygon fill="black" stroke="black" points="4514.24,-178.66 4503.71,-179.8 4512.65,-185.48 4514.24,-178.66"/>
</g>
<!-- [root] var.home_network_cidr (expand, reference) -->
<g id="node45" class="node">
<title>[root] var.home_network_cidr (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="4453.12" cy="-306" rx="240.46" ry="18"/>
<text text-anchor="middle" x="4453.12" y="-302.3" font-family="Times,serif" font-size="14.00">[root] var.home_network_cidr (expand, reference)</text>
</g>
<!-- [root] openstack_networking_secgroup_rule_v2.ssh_from_home (expand)&#45;&gt;[root] var.home_network_cidr (expand, reference) -->
<g id="edge52" class="edge">
<title>[root] openstack_networking_secgroup_rule_v2.ssh_from_home (expand)&#45;&gt;[root] var.home_network_cidr (expand, reference)</title>
<path fill="none" stroke="black" d="M4655.91,-359.97C4616.54,-349.68 4566.32,-336.57 4525.7,-325.96"/>
<polygon fill="black" stroke="black" points="4526.42,-322.53 4515.86,-323.39 4524.65,-329.3 4526.42,-322.53"/>
</g>
<!-- [root] openstack_networking_secgroup_v2.bastion (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] -->
<g id="edge53" class="edge">
<title>[root] openstack_networking_secgroup_v2.bastion (expand)&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;]</title>
<path fill="none" stroke="black" d="M4339.12,-143.7C4339.12,-135.98 4339.12,-126.71 4339.12,-118.11"/>
<polygon fill="black" stroke="black" points="4342.62,-118.1 4339.12,-108.1 4335.62,-118.1 4342.62,-118.1"/>
</g>
<!-- [root] var.bastion_flavor -->
<g id="node14" class="node">
<title>[root] var.bastion_flavor</title>
<polygon fill="none" stroke="black" points="892.62,-108 755.62,-108 755.62,-72 898.62,-72 898.62,-102 892.62,-108"/>
<polyline fill="none" stroke="black" points="892.62,-108 892.62,-102 "/>
<polyline fill="none" stroke="black" points="898.62,-102 892.62,-102 "/>
<text text-anchor="middle" x="827.12" y="-86.3" font-family="Times,serif" font-size="14.00">var.bastion_flavor</text>
</g>
<!-- [root] var.bastion_network_name -->
<g id="node15" class="node">
<title>[root] var.bastion_network_name</title>
<polygon fill="none" stroke="black" points="3660.12,-36 3460.12,-36 3460.12,0 3666.12,0 3666.12,-30 3660.12,-36"/>
<polyline fill="none" stroke="black" points="3660.12,-36 3660.12,-30 "/>
<polyline fill="none" stroke="black" points="3666.12,-30 3660.12,-30 "/>
<text text-anchor="middle" x="3563.12" y="-14.3" font-family="Times,serif" font-size="14.00">var.bastion_network_name</text>
</g>
<!-- [root] var.bastion_router_name -->
<g id="node16" class="node">
<title>[root] var.bastion_router_name</title>
<polygon fill="none" stroke="black" points="5042.62,-252 4855.62,-252 4855.62,-216 5048.62,-216 5048.62,-246 5042.62,-252"/>
<polyline fill="none" stroke="black" points="5042.62,-252 5042.62,-246 "/>
<polyline fill="none" stroke="black" points="5048.62,-246 5042.62,-246 "/>
<text text-anchor="middle" x="4952.12" y="-230.3" font-family="Times,serif" font-size="14.00">var.bastion_router_name</text>
</g>
<!-- [root] var.external_network_name -->
<g id="node17" class="node">
<title>[root] var.external_network_name</title>
<polygon fill="none" stroke="black" points="5577.62,-108 5370.62,-108 5370.62,-72 5583.62,-72 5583.62,-102 5577.62,-108"/>
<polyline fill="none" stroke="black" points="5577.62,-108 5577.62,-102 "/>
<polyline fill="none" stroke="black" points="5583.62,-102 5577.62,-102 "/>
<text text-anchor="middle" x="5477.12" y="-86.3" font-family="Times,serif" font-size="14.00">var.external_network_name</text>
</g>
<!-- [root] var.home_network_cidr -->
<g id="node18" class="node">
<title>[root] var.home_network_cidr</title>
<polygon fill="none" stroke="black" points="4538.12,-252 4362.12,-252 4362.12,-216 4544.12,-216 4544.12,-246 4538.12,-252"/>
<polyline fill="none" stroke="black" points="4538.12,-252 4538.12,-246 "/>
<polyline fill="none" stroke="black" points="4544.12,-246 4538.12,-246 "/>
<text text-anchor="middle" x="4453.12" y="-230.3" font-family="Times,serif" font-size="14.00">var.home_network_cidr</text>
</g>
<!-- [root] var.operator_ssh_public_key_path -->
<g id="node19" class="node">
<title>[root] var.operator_ssh_public_key_path</title>
<polygon fill="none" stroke="black" points="1857.12,-36 1607.12,-36 1607.12,0 1863.12,0 1863.12,-30 1857.12,-36"/>
<polyline fill="none" stroke="black" points="1857.12,-36 1857.12,-30 "/>
<polyline fill="none" stroke="black" points="1863.12,-30 1857.12,-30 "/>
<text text-anchor="middle" x="1735.12" y="-14.3" font-family="Times,serif" font-size="14.00">var.operator_ssh_public_key_path</text>
</g>
<!-- [root] var.bastion_network_name (expand, reference)&#45;&gt;[root] var.bastion_network_name -->
<g id="edge69" class="edge">
<title>[root] var.bastion_network_name (expand, reference)&#45;&gt;[root] var.bastion_network_name</title>
<path fill="none" stroke="black" d="M3563.12,-71.7C3563.12,-63.98 3563.12,-54.71 3563.12,-46.11"/>
<polygon fill="black" stroke="black" points="3566.62,-46.1 3563.12,-36.1 3559.62,-46.1 3566.62,-46.1"/>
</g>
<!-- [root] var.external_network_name (expand, reference)&#45;&gt;[root] var.external_network_name -->
<g id="edge71" class="edge">
<title>[root] var.external_network_name (expand, reference)&#45;&gt;[root] var.external_network_name</title>
<path fill="none" stroke="black" d="M5477.12,-143.7C5477.12,-135.98 5477.12,-126.71 5477.12,-118.11"/>
<polygon fill="black" stroke="black" points="5480.62,-118.1 5477.12,-108.1 5473.62,-118.1 5480.62,-118.1"/>
</g>
<!-- [root] var.bastion_router_name (expand, reference)&#45;&gt;[root] var.bastion_router_name -->
<g id="edge70" class="edge">
<title>[root] var.bastion_router_name (expand, reference)&#45;&gt;[root] var.bastion_router_name</title>
<path fill="none" stroke="black" d="M4986,-287.7C4980.77,-279.56 4974.42,-269.69 4968.65,-260.7"/>
<polygon fill="black" stroke="black" points="4971.47,-258.62 4963.12,-252.1 4965.58,-262.41 4971.47,-258.62"/>
</g>
<!-- [root] module.bastion (close) -->
<g id="node23" class="node">
<title>[root] module.bastion (close)</title>
<ellipse fill="none" stroke="black" cx="4084.12" cy="-522" rx="143.77" ry="18"/>
<text text-anchor="middle" x="4084.12" y="-518.3" font-family="Times,serif" font-size="14.00">[root] module.bastion (close)</text>
</g>
<!-- [root] module.bastion (close)&#45;&gt;[root] module.bastion.openstack_compute_floatingip_associate_v2.this (expand) -->
<g id="edge8" class="edge">
<title>[root] module.bastion (close)&#45;&gt;[root] module.bastion.openstack_compute_floatingip_associate_v2.this (expand)</title>
<path fill="none" stroke="black" d="M3992.14,-508.17C3954.26,-500.27 3910.95,-487.73 3875.12,-468 3854.75,-456.78 3858.09,-442.09 3837.12,-432 3806.23,-417.13 3738.74,-405.65 3669.08,-397.24"/>
<polygon fill="black" stroke="black" points="3669.14,-393.72 3658.79,-396.02 3668.31,-400.67 3669.14,-393.72"/>
</g>
<!-- [root] module.bastion.output.floating_ip_address (expand) -->
<g id="node24" class="node">
<title>[root] module.bastion.output.floating_ip_address (expand)</title>
<ellipse fill="none" stroke="black" cx="5014.12" cy="-450" rx="280.25" ry="18"/>
<text text-anchor="middle" x="5014.12" y="-446.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.output.floating_ip_address (expand)</text>
</g>
<!-- [root] module.bastion (close)&#45;&gt;[root] module.bastion.output.floating_ip_address (expand) -->
<g id="edge9" class="edge">
<title>[root] module.bastion (close)&#45;&gt;[root] module.bastion.output.floating_ip_address (expand)</title>
<path fill="none" stroke="black" d="M4203.8,-511.99C4362.41,-500.05 4643.81,-478.87 4829.69,-464.88"/>
<polygon fill="black" stroke="black" points="4830.14,-468.36 4839.85,-464.12 4829.61,-461.38 4830.14,-468.36"/>
</g>
<!-- [root] module.bastion.output.instance_id (expand) -->
<g id="node25" class="node">
<title>[root] module.bastion.output.instance_id (expand)</title>
<ellipse fill="none" stroke="black" cx="3585.12" cy="-450" rx="243.16" ry="18"/>
<text text-anchor="middle" x="3585.12" y="-446.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.output.instance_id (expand)</text>
</g>
<!-- [root] module.bastion (close)&#45;&gt;[root] module.bastion.output.instance_id (expand) -->
<g id="edge10" class="edge">
<title>[root] module.bastion (close)&#45;&gt;[root] module.bastion.output.instance_id (expand)</title>
<path fill="none" stroke="black" d="M3992.31,-508.12C3911,-496.71 3791.82,-480 3703.39,-467.59"/>
<polygon fill="black" stroke="black" points="3703.7,-464.1 3693.31,-466.18 3702.73,-471.03 3703.7,-464.1"/>
</g>
<!-- [root] module.bastion.output.floating_ip_address (expand)&#45;&gt;[root] module.bastion.openstack_networking_floatingip_v2.this (expand) -->
<g id="edge24" class="edge">
<title>[root] module.bastion.output.floating_ip_address (expand)&#45;&gt;[root] module.bastion.openstack_networking_floatingip_v2.this (expand)</title>
<path fill="none" stroke="black" d="M5152.69,-434.33C5255.02,-423.49 5394.92,-408.67 5504.2,-397.1"/>
<polygon fill="black" stroke="black" points="5504.76,-400.56 5514.34,-396.03 5504.03,-393.6 5504.76,-400.56"/>
</g>
<!-- [root] module.bastion.output.instance_id (expand)&#45;&gt;[root] module.bastion.openstack_compute_instance_v2.this (expand) -->
<g id="edge25" class="edge">
<title>[root] module.bastion.output.instance_id (expand)&#45;&gt;[root] module.bastion.openstack_compute_instance_v2.this (expand)</title>
<path fill="none" stroke="black" d="M3423.13,-436.57C3271.59,-424.93 3044.54,-407.51 2879.97,-394.88"/>
<polygon fill="black" stroke="black" points="2879.95,-391.36 2869.71,-394.09 2879.42,-398.34 2879.95,-391.36"/>
</g>
<!-- [root] module.bastion.var.image_name (expand, input) -->
<g id="node36" class="node">
<title>[root] module.bastion.var.image_name (expand, input)</title>
<ellipse fill="none" stroke="black" cx="2956.12" cy="-162" rx="262.65" ry="18"/>
<text text-anchor="middle" x="2956.12" y="-158.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.image_name (expand, input)</text>
</g>
<!-- [root] module.bastion.var.image_name (expand, reference)&#45;&gt;[root] module.bastion.var.image_name (expand, input) -->
<g id="edge30" class="edge">
<title>[root] module.bastion.var.image_name (expand, reference)&#45;&gt;[root] module.bastion.var.image_name (expand, input)</title>
<path fill="none" stroke="black" d="M3056.93,-216.05C3039.09,-206.67 3016.72,-194.89 2997.58,-184.82"/>
<polygon fill="black" stroke="black" points="2998.96,-181.59 2988.48,-180.03 2995.7,-187.79 2998.96,-181.59"/>
</g>
<!-- [root] module.bastion.var.instance_name (expand, input) -->
<g id="node37" class="node">
<title>[root] module.bastion.var.instance_name (expand, input)</title>
<ellipse fill="none" stroke="black" cx="1935.12" cy="-162" rx="272.95" ry="18"/>
<text text-anchor="middle" x="1935.12" y="-158.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.instance_name (expand, input)</text>
</g>
<!-- [root] module.bastion.var.instance_name (expand, reference)&#45;&gt;[root] module.bastion.var.instance_name (expand, input) -->
<g id="edge32" class="edge">
<title>[root] module.bastion.var.instance_name (expand, reference)&#45;&gt;[root] module.bastion.var.instance_name (expand, input)</title>
<path fill="none" stroke="black" d="M1528.79,-288.02C1572.65,-268.72 1647.58,-237.14 1714.12,-216 1756.68,-202.48 1804.8,-190.56 1845.25,-181.46"/>
<polygon fill="black" stroke="black" points="1846.09,-184.86 1855.09,-179.27 1844.57,-178.03 1846.09,-184.86"/>
</g>
<!-- [root] module.bastion.var.instance_type (expand, input) -->
<g id="node38" class="node">
<title>[root] module.bastion.var.instance_type (expand, input)</title>
<ellipse fill="none" stroke="black" cx="892.12" cy="-234" rx="268.35" ry="18"/>
<text text-anchor="middle" x="892.12" y="-230.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.instance_type (expand, input)</text>
</g>
<!-- [root] module.bastion.var.instance_type (expand, reference)&#45;&gt;[root] module.bastion.var.instance_type (expand, input) -->
<g id="edge35" class="edge">
<title>[root] module.bastion.var.instance_type (expand, reference)&#45;&gt;[root] module.bastion.var.instance_type (expand, input)</title>
<path fill="none" stroke="black" d="M892.12,-287.7C892.12,-279.98 892.12,-270.71 892.12,-262.11"/>
<polygon fill="black" stroke="black" points="895.62,-262.1 892.12,-252.1 888.62,-262.1 895.62,-262.1"/>
</g>
<!-- [root] module.bastion.var.keypair_name (expand, input) -->
<g id="node40" class="node">
<title>[root] module.bastion.var.keypair_name (expand, input)</title>
<ellipse fill="none" stroke="black" cx="1991.12" cy="-234" rx="268.35" ry="18"/>
<text text-anchor="middle" x="1991.12" y="-230.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.keypair_name (expand, input)</text>
</g>
<!-- [root] module.bastion.var.keypair_name (expand, reference)&#45;&gt;[root] module.bastion.var.keypair_name (expand, input) -->
<g id="edge38" class="edge">
<title>[root] module.bastion.var.keypair_name (expand, reference)&#45;&gt;[root] module.bastion.var.keypair_name (expand, input)</title>
<path fill="none" stroke="black" d="M2066.92,-288.05C2053.99,-279.01 2037.9,-267.74 2023.87,-257.93"/>
<polygon fill="black" stroke="black" points="2025.65,-254.9 2015.45,-252.03 2021.64,-260.63 2025.65,-254.9"/>
</g>
<!-- [root] module.bastion.var.network_id (expand, input) -->
<g id="node41" class="node">
<title>[root] module.bastion.var.network_id (expand, input)</title>
<ellipse fill="none" stroke="black" cx="2533.12" cy="-234" rx="255.35" ry="18"/>
<text text-anchor="middle" x="2533.12" y="-230.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.network_id (expand, input)</text>
</g>
<!-- [root] module.bastion.var.network_id (expand, reference)&#45;&gt;[root] module.bastion.var.network_id (expand, input) -->
<g id="edge41" class="edge">
<title>[root] module.bastion.var.network_id (expand, reference)&#45;&gt;[root] module.bastion.var.network_id (expand, input)</title>
<path fill="none" stroke="black" d="M2639.23,-288.05C2620.29,-278.58 2596.48,-266.68 2576.22,-256.55"/>
<polygon fill="black" stroke="black" points="2577.7,-253.37 2567.19,-252.03 2574.57,-259.63 2577.7,-253.37"/>
</g>
<!-- [root] module.bastion.var.security_group_names (expand, input) -->
<g id="node42" class="node">
<title>[root] module.bastion.var.security_group_names (expand, input)</title>
<ellipse fill="none" stroke="black" cx="3735.12" cy="-234" rx="308.15" ry="18"/>
<text text-anchor="middle" x="3735.12" y="-230.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.security_group_names (expand, input)</text>
</g>
<!-- [root] module.bastion.var.security_group_names (expand, reference)&#45;&gt;[root] module.bastion.var.security_group_names (expand, input) -->
<g id="edge44" class="edge">
<title>[root] module.bastion.var.security_group_names (expand, reference)&#45;&gt;[root] module.bastion.var.security_group_names (expand, input)</title>
<path fill="none" stroke="black" d="M3720.07,-287.7C3722.3,-279.9 3724.98,-270.51 3727.46,-261.83"/>
<polygon fill="black" stroke="black" points="3730.86,-262.68 3730.24,-252.1 3724.12,-260.76 3730.86,-262.68"/>
</g>
<!-- [root] module.bastion.var.ssh_public_key (expand, input) -->
<g id="node43" class="node">
<title>[root] module.bastion.var.ssh_public_key (expand, input)</title>
<ellipse fill="none" stroke="black" cx="1333.12" cy="-162" rx="272.95" ry="18"/>
<text text-anchor="middle" x="1333.12" y="-158.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.ssh_public_key (expand, input)</text>
</g>
<!-- [root] module.bastion.var.ssh_public_key (expand, reference)&#45;&gt;[root] module.bastion.var.ssh_public_key (expand, input) -->
<g id="edge47" class="edge">
<title>[root] module.bastion.var.ssh_public_key (expand, reference)&#45;&gt;[root] module.bastion.var.ssh_public_key (expand, input)</title>
<path fill="none" stroke="black" d="M342.09,-288.23C404.62,-267.56 516.55,-233.09 615.12,-216 665.02,-207.35 939.47,-188.41 1134.18,-175.68"/>
<polygon fill="black" stroke="black" points="1134.51,-179.16 1144.26,-175.02 1134.06,-172.18 1134.51,-179.16"/>
</g>
<!-- [root] module.bastion.var.external_network_name (expand, input) -->
<g id="node35" class="node">
<title>[root] module.bastion.var.external_network_name (expand, input)</title>
<ellipse fill="none" stroke="black" cx="5420.12" cy="-234" rx="315.44" ry="18"/>
<text text-anchor="middle" x="5420.12" y="-230.3" font-family="Times,serif" font-size="14.00">[root] module.bastion.var.external_network_name (expand, input)</text>
</g>
<!-- [root] module.bastion.var.external_network_name (expand, reference)&#45;&gt;[root] module.bastion.var.external_network_name (expand, input) -->
<g id="edge28" class="edge">
<title>[root] module.bastion.var.external_network_name (expand, reference)&#45;&gt;[root] module.bastion.var.external_network_name (expand, input)</title>
<path fill="none" stroke="black" d="M5662.76,-288.41C5615.42,-277.99 5554.26,-264.53 5505.18,-253.72"/>
<polygon fill="black" stroke="black" points="5505.74,-250.26 5495.22,-251.53 5504.23,-257.1 5505.74,-250.26"/>
</g>
<!-- [root] module.bastion.var.external_network_name (expand, input)&#45;&gt;[root] var.external_network_name (expand, reference) -->
<g id="edge27" class="edge">
<title>[root] module.bastion.var.external_network_name (expand, input)&#45;&gt;[root] var.external_network_name (expand, reference)</title>
<path fill="none" stroke="black" d="M5434.21,-215.7C5441.05,-207.3 5449.38,-197.07 5456.88,-187.86"/>
<polygon fill="black" stroke="black" points="5459.6,-190.07 5463.2,-180.1 5454.17,-185.65 5459.6,-190.07"/>
</g>
<!-- [root] module.bastion.var.external_network_name (expand, input)&#45;&gt;[root] module.bastion (expand) -->
<g id="edge26" class="edge">
<title>[root] module.bastion.var.external_network_name (expand, input)&#45;&gt;[root] module.bastion (expand)</title>
<path fill="none" stroke="black" d="M5291.56,-217.52C5115.99,-197.03 4791.24,-161.47 4513.12,-144 4426.24,-138.54 3200.18,-106.55 2756.73,-95.09"/>
<polygon fill="black" stroke="black" points="2756.81,-91.59 2746.72,-94.83 2756.63,-98.58 2756.81,-91.59"/>
</g>
<!-- [root] module.bastion.var.image_name (expand, input)&#45;&gt;[root] module.bastion (expand) -->
<g id="edge29" class="edge">
<title>[root] module.bastion.var.image_name (expand, input)&#45;&gt;[root] module.bastion (expand)</title>
<path fill="none" stroke="black" d="M2873.54,-144.85C2816.66,-133.73 2741.26,-118.99 2683.74,-107.74"/>
<polygon fill="black" stroke="black" points="2684.06,-104.24 2673.58,-105.75 2682.72,-111.11 2684.06,-104.24"/>
</g>
<!-- [root] module.bastion.var.instance_name (expand, input)&#45;&gt;[root] module.bastion (expand) -->
<g id="edge31" class="edge">
<title>[root] module.bastion.var.instance_name (expand, input)&#45;&gt;[root] module.bastion (expand)</title>
<path fill="none" stroke="black" d="M2072.9,-146.45C2192.41,-133.84 2363.66,-115.75 2477.76,-103.71"/>
<polygon fill="black" stroke="black" points="2478.36,-107.16 2487.93,-102.63 2477.62,-100.2 2478.36,-107.16"/>
</g>
<!-- [root] module.bastion.var.instance_type (expand, input)&#45;&gt;[root] module.bastion (expand) -->
<g id="edge33" class="edge">
<title>[root] module.bastion.var.instance_type (expand, input)&#45;&gt;[root] module.bastion (expand)</title>
<path fill="none" stroke="black" d="M1159.32,-231.99C1330.68,-227.8 1535.46,-215.17 1615.12,-180 1636.41,-170.6 1631.76,-153.21 1653.12,-144 1688.72,-128.65 2185.43,-107.13 2444.03,-96.88"/>
<polygon fill="black" stroke="black" points="2444.41,-100.36 2454.26,-96.47 2444.13,-93.37 2444.41,-100.36"/>
</g>
<!-- [root] var.bastion_flavor (expand, reference) -->
<g id="node39" class="node">
<title>[root] var.bastion_flavor (expand, reference)</title>
<ellipse fill="none" stroke="black" cx="827.12" cy="-162" rx="215.26" ry="18"/>
<text text-anchor="middle" x="827.12" y="-158.3" font-family="Times,serif" font-size="14.00">[root] var.bastion_flavor (expand, reference)</text>
</g>
<!-- [root] module.bastion.var.instance_type (expand, input)&#45;&gt;[root] var.bastion_flavor (expand, reference) -->
<g id="edge34" class="edge">
<title>[root] module.bastion.var.instance_type (expand, input)&#45;&gt;[root] var.bastion_flavor (expand, reference)</title>
<path fill="none" stroke="black" d="M876.06,-215.7C868.19,-207.22 858.57,-196.86 849.95,-187.58"/>
<polygon fill="black" stroke="black" points="852.38,-185.05 843.01,-180.1 847.25,-189.81 852.38,-185.05"/>
</g>
<!-- [root] var.bastion_flavor (expand, reference)&#45;&gt;[root] var.bastion_flavor -->
<g id="edge68" class="edge">
<title>[root] var.bastion_flavor (expand, reference)&#45;&gt;[root] var.bastion_flavor</title>
<path fill="none" stroke="black" d="M827.12,-143.7C827.12,-135.98 827.12,-126.71 827.12,-118.11"/>
<polygon fill="black" stroke="black" points="830.62,-118.1 827.12,-108.1 823.62,-118.1 830.62,-118.1"/>
</g>
<!-- [root] module.bastion.var.keypair_name (expand, input)&#45;&gt;[root] openstack_compute_keypair_v2.operator (expand) -->
<g id="edge37" class="edge">
<title>[root] module.bastion.var.keypair_name (expand, input)&#45;&gt;[root] openstack_compute_keypair_v2.operator (expand)</title>
<path fill="none" stroke="black" d="M2080.14,-216.94C2138.1,-206.48 2213.96,-192.8 2274.76,-181.83"/>
<polygon fill="black" stroke="black" points="2275.55,-185.24 2284.77,-180.02 2274.31,-178.35 2275.55,-185.24"/>
</g>
<!-- [root] module.bastion.var.keypair_name (expand, input)&#45;&gt;[root] module.bastion (expand) -->
<g id="edge36" class="edge">
<title>[root] module.bastion.var.keypair_name (expand, input)&#45;&gt;[root] module.bastion (expand)</title>
<path fill="none" stroke="black" d="M2162.64,-220.11C2317.94,-207.87 2524.91,-189.91 2541.12,-180 2553.44,-172.47 2572.15,-140.58 2584.74,-117.12"/>
<polygon fill="black" stroke="black" points="2587.98,-118.46 2589.56,-107.99 2581.79,-115.2 2587.98,-118.46"/>
</g>
<!-- [root] module.bastion.var.network_id (expand, input)&#45;&gt;[root] data.openstack_networking_network_v2.bastion_net (expand) -->
<g id="edge39" class="edge">
<title>[root] module.bastion.var.network_id (expand, input)&#45;&gt;[root] data.openstack_networking_network_v2.bastion_net (expand)</title>
<path fill="none" stroke="black" d="M2712.72,-221.2C2741.28,-219.4 2770.51,-217.61 2798.12,-216 3076.95,-199.74 3399.21,-183.23 3603.29,-173.05"/>
<polygon fill="black" stroke="black" points="3603.71,-176.53 3613.52,-172.54 3603.36,-169.54 3603.71,-176.53"/>
</g>
<!-- [root] module.bastion.var.network_id (expand, input)&#45;&gt;[root] module.bastion (expand) -->
<g id="edge40" class="edge">
<title>[root] module.bastion.var.network_id (expand, input)&#45;&gt;[root] module.bastion (expand)</title>
<path fill="none" stroke="black" d="M2549.47,-215.56C2557.89,-205.76 2567.71,-192.92 2574.12,-180 2583.88,-160.35 2590.07,-136.22 2593.72,-118.05"/>
<polygon fill="black" stroke="black" points="2597.18,-118.59 2595.58,-108.11 2590.3,-117.3 2597.18,-118.59"/>
</g>
<!-- [root] module.bastion.var.security_group_names (expand, input)&#45;&gt;[root] openstack_networking_secgroup_v2.bastion (expand) -->
<g id="edge43" class="edge">
<title>[root] module.bastion.var.security_group_names (expand, input)&#45;&gt;[root] openstack_networking_secgroup_v2.bastion (expand)</title>
<path fill="none" stroke="black" d="M3866.93,-217.72C3959.72,-206.97 4084.33,-192.53 4182.25,-181.18"/>
<polygon fill="black" stroke="black" points="4182.71,-184.65 4192.24,-180.02 4181.9,-177.7 4182.71,-184.65"/>
</g>
<!-- [root] module.bastion.var.security_group_names (expand, input)&#45;&gt;[root] module.bastion (expand) -->
<g id="edge42" class="edge">
<title>[root] module.bastion.var.security_group_names (expand, input)&#45;&gt;[root] module.bastion (expand)</title>
<path fill="none" stroke="black" d="M3654.68,-216.57C3554.98,-196.75 3379.67,-163.64 3228.12,-144 3062.4,-122.53 2870.96,-107.85 2743.01,-99.48"/>
<polygon fill="black" stroke="black" points="2742.97,-95.97 2732.76,-98.81 2742.51,-102.95 2742.97,-95.97"/>
</g>
<!-- [root] module.bastion.var.ssh_public_key (expand, input)&#45;&gt;[root] module.bastion (expand) -->
<g id="edge45" class="edge">
<title>[root] module.bastion.var.ssh_public_key (expand, input)&#45;&gt;[root] module.bastion (expand)</title>
<path fill="none" stroke="black" d="M1527.64,-149.35C1558.57,-147.53 1590.22,-145.7 1620.12,-144 1914.71,-127.29 2259.27,-108.88 2450.72,-98.76"/>
<polygon fill="black" stroke="black" points="2451.04,-102.24 2460.84,-98.22 2450.67,-95.25 2451.04,-102.24"/>
</g>
<!-- [root] module.bastion.var.ssh_public_key (expand, input)&#45;&gt;[root] var.operator_ssh_public_key_path (expand, reference) -->
<g id="edge46" class="edge">
<title>[root] module.bastion.var.ssh_public_key (expand, input)&#45;&gt;[root] var.operator_ssh_public_key_path (expand, reference)</title>
<path fill="none" stroke="black" d="M1424.85,-145.03C1486.77,-134.25 1568.56,-120 1632.63,-108.85"/>
<polygon fill="black" stroke="black" points="1633.5,-112.25 1642.75,-107.08 1632.3,-105.35 1633.5,-112.25"/>
</g>
<!-- [root] var.operator_ssh_public_key_path (expand, reference)&#45;&gt;[root] var.operator_ssh_public_key_path -->
<g id="edge73" class="edge">
<title>[root] var.operator_ssh_public_key_path (expand, reference)&#45;&gt;[root] var.operator_ssh_public_key_path</title>
<path fill="none" stroke="black" d="M1735.12,-71.7C1735.12,-63.98 1735.12,-54.71 1735.12,-46.11"/>
<polygon fill="black" stroke="black" points="1738.62,-46.1 1735.12,-36.1 1731.62,-46.1 1738.62,-46.1"/>
</g>
<!-- [root] var.home_network_cidr (expand, reference)&#45;&gt;[root] var.home_network_cidr -->
<g id="edge72" class="edge">
<title>[root] var.home_network_cidr (expand, reference)&#45;&gt;[root] var.home_network_cidr</title>
<path fill="none" stroke="black" d="M4453.12,-287.7C4453.12,-279.98 4453.12,-270.71 4453.12,-262.11"/>
<polygon fill="black" stroke="black" points="4456.62,-262.1 4453.12,-252.1 4449.62,-262.1 4456.62,-262.1"/>
</g>
<!-- [root] output.bastion_floating_ip (expand) -->
<g id="node46" class="node">
<title>[root] output.bastion_floating_ip (expand)</title>
<ellipse fill="none" stroke="black" cx="4761.12" cy="-522" rx="203.36" ry="18"/>
<text text-anchor="middle" x="4761.12" y="-518.3" font-family="Times,serif" font-size="14.00">[root] output.bastion_floating_ip (expand)</text>
</g>
<!-- [root] output.bastion_floating_ip (expand)&#45;&gt;[root] module.bastion.output.floating_ip_address (expand) -->
<g id="edge54" class="edge">
<title>[root] output.bastion_floating_ip (expand)&#45;&gt;[root] module.bastion.output.floating_ip_address (expand)</title>
<path fill="none" stroke="black" d="M4819.8,-504.76C4856.94,-494.49 4905.16,-481.15 4944.27,-470.33"/>
<polygon fill="black" stroke="black" points="4945.3,-473.67 4954.01,-467.63 4943.43,-466.93 4945.3,-473.67"/>
</g>
<!-- [root] output.bastion_instance_id (expand) -->
<g id="node47" class="node">
<title>[root] output.bastion_instance_id (expand)</title>
<ellipse fill="none" stroke="black" cx="3672.12" cy="-522" rx="207.16" ry="18"/>
<text text-anchor="middle" x="3672.12" y="-518.3" font-family="Times,serif" font-size="14.00">[root] output.bastion_instance_id (expand)</text>
</g>
<!-- [root] output.bastion_instance_id (expand)&#45;&gt;[root] module.bastion.output.instance_id (expand) -->
<g id="edge55" class="edge">
<title>[root] output.bastion_instance_id (expand)&#45;&gt;[root] module.bastion.output.instance_id (expand)</title>
<path fill="none" stroke="black" d="M3651.06,-504.05C3640.03,-495.18 3626.35,-484.17 3614.31,-474.48"/>
<polygon fill="black" stroke="black" points="3616.28,-471.57 3606.29,-468.03 3611.89,-477.03 3616.28,-471.57"/>
</g>
<!-- [root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close) -->
<g id="node48" class="node">
<title>[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)</title>
<ellipse fill="none" stroke="black" cx="4300.12" cy="-450" rx="415.93" ry="18"/>
<text text-anchor="middle" x="4300.12" y="-446.3" font-family="Times,serif" font-size="14.00">[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)</text>
</g>
<!-- [root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] data.openstack_networking_network_v2.external (expand) -->
<g id="edge56" class="edge">
<title>[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] data.openstack_networking_network_v2.external (expand)</title>
<path fill="none" stroke="black" d="M4582.07,-436.76C4892.56,-423 5349.38,-401.83 5357.12,-396 5397.66,-365.48 5354.33,-319.47 5394.12,-288 5397.66,-285.21 5589.08,-266.96 5743.42,-252.64"/>
<polygon fill="black" stroke="black" points="5743.9,-256.11 5753.53,-251.7 5743.25,-249.14 5743.9,-256.11"/>
</g>
<!-- [root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] data.openstack_networking_router_v2.bastion_router (expand) -->
<g id="edge57" class="edge">
<title>[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] data.openstack_networking_router_v2.bastion_router (expand)</title>
<path fill="none" stroke="black" d="M4484.08,-433.83C4618.37,-422.76 4800.6,-407.74 4940.35,-396.21"/>
<polygon fill="black" stroke="black" points="4940.66,-399.7 4950.34,-395.39 4940.08,-392.72 4940.66,-399.7"/>
</g>
<!-- [root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] data.openstack_networking_subnet_v2.bastion_net (expand) -->
<g id="edge58" class="edge">
<title>[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] data.openstack_networking_subnet_v2.bastion_net (expand)</title>
<path fill="none" stroke="black" d="M4205.82,-432.46C4146.56,-422.06 4069.95,-408.62 4008.38,-397.82"/>
<polygon fill="black" stroke="black" points="4008.7,-394.32 3998.24,-396.04 4007.49,-401.21 4008.7,-394.32"/>
</g>
<!-- [root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] module.bastion.openstack_compute_floatingip_associate_v2.this (expand) -->
<g id="edge59" class="edge">
<title>[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] module.bastion.openstack_compute_floatingip_associate_v2.this (expand)</title>
<path fill="none" stroke="black" d="M4117.21,-433.81C3986.34,-422.94 3809.74,-408.28 3672.13,-396.85"/>
<polygon fill="black" stroke="black" points="3672.13,-393.34 3661.87,-396 3671.55,-400.32 3672.13,-393.34"/>
</g>
<!-- [root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] module.bastion.openstack_compute_instance_v2.this (expand) -->
<g id="edge60" class="edge">
<title>[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] module.bastion.openstack_compute_instance_v2.this (expand)</title>
<path fill="none" stroke="black" d="M4016.72,-436.81C3692.24,-422.85 3168.47,-400.31 2880.07,-387.9"/>
<polygon fill="black" stroke="black" points="2880.06,-384.4 2869.92,-387.47 2879.76,-391.39 2880.06,-384.4"/>
</g>
<!-- [root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] module.bastion.openstack_networking_floatingip_v2.this (expand) -->
<g id="edge61" class="edge">
<title>[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] module.bastion.openstack_networking_floatingip_v2.this (expand)</title>
<path fill="none" stroke="black" d="M4574.57,-436.46C4794.8,-426.2 5111.87,-410.99 5389.12,-396 5410.44,-394.85 5432.66,-393.6 5454.86,-392.33"/>
<polygon fill="black" stroke="black" points="5455.28,-395.81 5465.06,-391.74 5454.87,-388.82 5455.28,-395.81"/>
</g>
<!-- [root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] openstack_networking_secgroup_rule_v2.egress_all (expand) -->
<g id="edge62" class="edge">
<title>[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] openstack_networking_secgroup_rule_v2.egress_all (expand)</title>
<path fill="none" stroke="black" d="M4300.12,-431.7C4300.12,-423.98 4300.12,-414.71 4300.12,-406.11"/>
<polygon fill="black" stroke="black" points="4303.62,-406.1 4300.12,-396.1 4296.62,-406.1 4303.62,-406.1"/>
</g>
<!-- [root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] openstack_networking_secgroup_rule_v2.ssh_from_home (expand) -->
<g id="edge63" class="edge">
<title>[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)&#45;&gt;[root] openstack_networking_secgroup_rule_v2.ssh_from_home (expand)</title>
<path fill="none" stroke="black" d="M4399.36,-432.5C4462.14,-422.06 4543.45,-408.54 4608.62,-397.71"/>
<polygon fill="black" stroke="black" points="4609.23,-401.15 4618.52,-396.06 4608.09,-394.25 4609.23,-401.15"/>
</g>
<!-- [root] root -->
<g id="node49" class="node">
<title>[root] root</title>
<ellipse fill="none" stroke="black" cx="4170.12" cy="-594" rx="58.49" ry="18"/>
<text text-anchor="middle" x="4170.12" y="-590.3" font-family="Times,serif" font-size="14.00">[root] root</text>
</g>
<!-- [root] root&#45;&gt;[root] module.bastion (close) -->
<g id="edge64" class="edge">
<title>[root] root&#45;&gt;[root] module.bastion (close)</title>
<path fill="none" stroke="black" d="M4150.18,-576.76C4139.02,-567.69 4124.93,-556.22 4112.63,-546.21"/>
<polygon fill="black" stroke="black" points="4114.83,-543.48 4104.86,-539.88 4110.41,-548.91 4114.83,-543.48"/>
</g>
<!-- [root] root&#45;&gt;[root] output.bastion_floating_ip (expand) -->
<g id="edge65" class="edge">
<title>[root] root&#45;&gt;[root] output.bastion_floating_ip (expand)</title>
<path fill="none" stroke="black" d="M4223.61,-586.66C4315.74,-575.75 4506.73,-553.13 4634.43,-538.01"/>
<polygon fill="black" stroke="black" points="4635.14,-541.45 4644.66,-536.79 4634.32,-534.49 4635.14,-541.45"/>
</g>
<!-- [root] root&#45;&gt;[root] output.bastion_instance_id (expand) -->
<g id="edge66" class="edge">
<title>[root] root&#45;&gt;[root] output.bastion_instance_id (expand)</title>
<path fill="none" stroke="black" d="M4117.77,-585.64C4039.51,-574.64 3890.09,-553.64 3785.94,-539"/>
<polygon fill="black" stroke="black" points="3786.4,-535.53 3776.01,-537.6 3785.43,-542.46 3786.4,-535.53"/>
</g>
<!-- [root] root&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close) -->
<g id="edge67" class="edge">
<title>[root] root&#45;&gt;[root] provider[&quot;registry.opentofu.org/terraform&#45;provider&#45;openstack/openstack&quot;] (close)</title>
<path fill="none" stroke="black" d="M4193.2,-577.29C4206.79,-567.44 4223.86,-553.99 4237.12,-540 4255.59,-520.52 4272.93,-495.31 4284.72,-476.7"/>
<polygon fill="black" stroke="black" points="4287.73,-478.49 4290.05,-468.15 4281.79,-474.79 4287.73,-478.49"/>
</g>
</g>
</svg>
